[project]
name = "cookiecutter-pypackage"
version = "0.2.0"
description = "Cookiecutter template for a Python package"
readme = "README.md"
requires-python = ">=3.10"
license = { text = "BSD" }
authors = [
    { name = "Audrey M. Roy Greenfeld", email = "audrey@feldroy.com" }
]
keywords = ["cookiecutter", "template", "package"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Natural Language :: English",
    "License :: OSI Approved :: BSD License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: Implementation :: CPython",
    "Topic :: Software Development",
]
dependencies = [
    "cookiecutter>=2.6.0",
    "ruff>=0.12.4",
    "pytest>=8.4.1",
    "pytest-cookies>=0.7.0",
    "typer>=0.16.0",
    "nox>=2025.5.1",
    "alabaster>=1.0.0",
    "watchdog>=6.0.0",
]

[project.urls]
homepage = "https://github.com/audreyfeldroy/cookiecutter-pypackage"

[tool.ruff]
exclude = [
	"*cookiecutter.project_slug*"
	]

[tool.pytest.ini_options]
testpaths = [
    "tests",
]

