dist: xenial   # required for Python >= 3.7
language: python
os:
  - linux
python:
  - "3.6"
  - "3.7"
jobs:
  include:
    - os: osx
      language: shell
    - env: ALLOW_FAIL=true
      python: "3.8"
  allow_failures:
    - env: ALLOW_FAIL=true

before_install:
  # Useful for debugging Travis CI environment
  - printenv
install:
  # Python 3.x is default
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda install setuptools
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  # Prepare env with Python version
  - conda create -n {{ cookiecutter.project_slug }} -c conda-forge python=$TRAVIS_PYTHON_VERSION
  # Update now the env with our environment
  - conda env update -f environment.yml
  - source activate {{ cookiecutter.project_slug }}
  # Packages for testing, generating docs and installing WPS
  - make develop
before_script:
  # Start WPS service on port {{ cookiecutter.http_port }} on 0.0.0.0
  - {{ cookiecutter.project_slug }} start --daemon --bind-host 0.0.0.0 --port {{ cookiecutter.http_port }}
  - sleep 2
script:
  - pytest
  - make test-notebooks
  - flake8
  - make docs
