name: {{ cookiecutter.project_slug }}
channels:
#- conda-forge
- defaults
dependencies:
- pip
- pywps>=4.2
- jinja2
- click
- psutil
# tests
- pytest
- pytest-notebook
- bump2version
- ipython
- nbsphinx
- nbval
- nbconvert
#- pip:
#  - -e git+https://github.com/geopython/pywps@master#egg=pywps
